// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvODButPg5PiXDI1lzVZMtQBj7iMdCV58',
    appId: '1:235450574163:android:90f5d402f759ef0a67eda6',
    messagingSenderId: '235450574163',
    projectId: 'simple-calculator-a95d5',
    storageBucket: 'simple-calculator-a95d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3aKzfV0J38mrskze-i_oYkUpibXHaUU8',
    appId: '1:235450574163:ios:5adba34e9fe0079767eda6',
    messagingSenderId: '235450574163',
    projectId: 'simple-calculator-a95d5',
    storageBucket: 'simple-calculator-a95d5.appspot.com',
    iosClientId: '235450574163-j3kvi3ovafmjhiamri7kuv9cc69u98sk.apps.googleusercontent.com',
    iosBundleId: 'com.simple.calculator.plus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3aKzfV0J38mrskze-i_oYkUpibXHaUU8',
    appId: '1:235450574163:ios:5adba34e9fe0079767eda6',
    messagingSenderId: '235450574163',
    projectId: 'simple-calculator-a95d5',
    storageBucket: 'simple-calculator-a95d5.appspot.com',
    iosClientId: '235450574163-j3kvi3ovafmjhiamri7kuv9cc69u98sk.apps.googleusercontent.com',
    iosBundleId: 'com.simple.calculator.plus',
  );
}
